### ISSUE TITLE
Project file structure issues

### ISSUE THREAD

**Issue by tbtommyb** [FAC9/TheReposWebsite#51]
- There is a `javascript` directory but it only contains an empty .js file, so you could remove it.
- Really minor point but it would be helpful if the project images were in a sub-directory separate from your profile pictures.

**Comment by SavageWilliam** [comment]
We've kept the ```javascript``` directory but it is currently not linked in the HTML. Reason being, it's scaffolding for later work when we add further features... ;) (wishful thinking) but you get the point.
