### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by marisid** [FAC9/TheReposWebsite#53]
Hi all! 

That's a very nice and clean website, good job :smiley:

I was just checking the accessibility of your webpage through Tenon.io (go and have a look, it's very useful), as mentioned in the FAC9 book,[see section 'Build a blog using GitHub Pages'](https://foundersandcoders.gitbooks.io/fac9/content/week1/project.html).

A quick review of your code gave me 40 issues, mainly related with missing attributes (such as alt attributes for photos, which can be added easily).

**Comment by tbtommyb** [comment]
You can see the report here: https://goo.gl/MQV8Cm

**Comment by limeyb7** [comment]
Fixed the alt tags issue

**Comment by limeyb7** [comment]
Also fixed missing text from links
