### ISSUE TITLE
.DS_Store

### ISSUE THREAD

**Issue by msmichellegar** [FAC9/TheReposWebsite#60]
Awesome work! :)

You've pushed your `.DS_Store` file to GitHub. This is a weird temporary file that Macs create which is best to keep from cluttering the repo. Either delete the file locally in your editor, or [create a `.gitignore` file](https://help.github.com/articles/ignoring-files/) to prevent it from being pushed (preferably the latter).

**Comment by shireenzoaby** [comment]
Deleted :).

**Comment by msmichellegar** [comment]
Perfect! 👍
